export const CURRENCIES = ['GBP', 'EUR', 'USD'];
export const DEFAULT_BASE_CURRENCY = 'GBP';
export const DEFAULT_TO_CURRENCY = 'EUR';
export const SELECT_BASE_CURRENCY = 'SELECT_BASE_CURRENCY';
export const SELECT_TO_CURRENCY = 'SELECT_TO_CURRENCY';
